// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWgwBn5blXJGV1BzQzTWLpcKNy8Kei9zc',
    appId: '1:301547038673:web:af986c2bb15e09360862f0',
    messagingSenderId: '301547038673',
    projectId: 'av10-01',
    authDomain: 'av10-01.firebaseapp.com',
    databaseURL: 'https://av10-01-default-rtdb.firebaseio.com',
    storageBucket: 'av10-01.firebasestorage.app',
    measurementId: 'G-FZM9XRRG7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARtbJodEsv240e_EyWUt1cZ7a53M8igb4',
    appId: '1:301547038673:android:2e2764c1b9bd940b0862f0',
    messagingSenderId: '301547038673',
    projectId: 'av10-01',
    databaseURL: 'https://av10-01-default-rtdb.firebaseio.com',
    storageBucket: 'av10-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1yeUq11A8-4MD9y_nqH7coG2qJaFc8I',
    appId: '1:301547038673:ios:f1d580fd125bc0420862f0',
    messagingSenderId: '301547038673',
    projectId: 'av10-01',
    databaseURL: 'https://av10-01-default-rtdb.firebaseio.com',
    storageBucket: 'av10-01.firebasestorage.app',
    iosBundleId: 'com.example.it01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj1yeUq11A8-4MD9y_nqH7coG2qJaFc8I',
    appId: '1:301547038673:ios:f1d580fd125bc0420862f0',
    messagingSenderId: '301547038673',
    projectId: 'av10-01',
    databaseURL: 'https://av10-01-default-rtdb.firebaseio.com',
    storageBucket: 'av10-01.firebasestorage.app',
    iosBundleId: 'com.example.it01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWgwBn5blXJGV1BzQzTWLpcKNy8Kei9zc',
    appId: '1:301547038673:web:bcc2b236111bf1f50862f0',
    messagingSenderId: '301547038673',
    projectId: 'av10-01',
    authDomain: 'av10-01.firebaseapp.com',
    databaseURL: 'https://av10-01-default-rtdb.firebaseio.com',
    storageBucket: 'av10-01.firebasestorage.app',
    measurementId: 'G-67X7WQ3LXJ',
  );
}
